# Generated by Django 2.2.14 on 2020-11-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
